# Generated by Django 4.1.3 on 2022-11-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='store',
            field=models.CharField(default='', max_length=100),
        ),
    ]
