# Generated by Django 4.1.3 on 2022-11-14 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_address_orderitem_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
