# Generated by Django 4.1.3 on 2022-11-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_post_no_of_likes_alter_postimage_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
