# Generated by Django 4.1.3 on 2022-11-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_comment_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
